import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const colors = ["#C6A96B", "#8F9AA8", "#6F5F3D", "#D8C690", "#6B7280", "#A78B67", "#9CA3AF"];
const tip = { background: "#111217", border: "1px solid rgba(198,169,107,.25)", borderRadius: 12 };
const Card = ({ title, children }) => <article className="rounded-2xl border border-white/10 bg-[#1A1D23] p-5 shadow-lg"><h2 className="mb-5 text-xl font-medium">{title}</h2><div className="h-72">{children}</div></article>;

export function ModeRevenueChart({ data }) { return <Card title="現場 VS 外送"><ResponsiveContainer><BarChart data={data}><CartesianGrid stroke="rgba(255,255,255,.08)" vertical={false}/><XAxis dataKey="name" stroke="#a1a1aa"/><YAxis stroke="#a1a1aa"/><Tooltip contentStyle={tip}/><Bar dataKey="value" fill="#C6A96B" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></Card>; }
export function ExpenseCategoryChart({ data }) { return <Card title="支出分類比例"><ResponsiveContainer><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius="50%" outerRadius="78%">{data.map((item,index)=><Cell key={item.name} fill={colors[index%colors.length]}/>)}</Pie><Tooltip contentStyle={tip}/><Legend/></PieChart></ResponsiveContainer></Card>; }
export function ExpenseTrendChart({ data }) { return <Card title="支出趨勢"><ResponsiveContainer><LineChart data={data}><CartesianGrid stroke="rgba(255,255,255,.08)" vertical={false}/><XAxis dataKey="name" stroke="#a1a1aa"/><YAxis stroke="#a1a1aa"/><Tooltip contentStyle={tip}/><Line type="monotone" dataKey="value" stroke="#C6A96B" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></Card>; }
export function LossDistributionChart({ data }) { return <Card title="損耗分析"><ResponsiveContainer><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius="50%" outerRadius="78%">{data.map((item,index)=><Cell key={item.name} fill={colors[index%colors.length]}/>)}</Pie><Tooltip contentStyle={tip}/><Legend/></PieChart></ResponsiveContainer></Card>; }
export function LossTrendChart({ data }) { return <Card title="損耗趨勢"><ResponsiveContainer><LineChart data={data}><CartesianGrid stroke="rgba(255,255,255,.08)" vertical={false}/><XAxis dataKey="name" stroke="#a1a1aa"/><YAxis stroke="#a1a1aa"/><Tooltip contentStyle={tip}/><Line type="monotone" dataKey="value" stroke="#D8C690" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></Card>; }
export function CashFlowChart({ inflow, outflow }) { const data=[{name:"現金流入",value:inflow},{name:"現金流出",value:outflow}]; return <Card title="現金流分析"><ResponsiveContainer><BarChart data={data}><CartesianGrid stroke="rgba(255,255,255,.08)" vertical={false}/><XAxis dataKey="name" stroke="#a1a1aa"/><YAxis stroke="#a1a1aa"/><Tooltip contentStyle={tip}/><Bar dataKey="value" fill="#C6A96B" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></Card>; }
export function CashBalanceTrendChart({ data }) { return <Card title="資金餘額趨勢"><ResponsiveContainer><LineChart data={data}><CartesianGrid stroke="rgba(255,255,255,.08)" vertical={false}/><XAxis dataKey="name" stroke="#a1a1aa"/><YAxis stroke="#a1a1aa"/><Tooltip contentStyle={tip}/><Legend/><Line type="monotone" dataKey="cash" name="店內現金" stroke="#C6A96B" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="bank" name="銀行戶頭" stroke="#8F9AA8" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></Card>; }
