export function OrderPanel({ items, total, itemCount, mode, paymentMethod, onPaymentMethodChange, onRemoveOne, onCheckout }) {
  const isDelivery = mode === "delivery";
  const accentText = isDelivery ? "text-emerald-400" : "text-[#C6A96B]";
  const badgeClass = isDelivery ? "border-emerald-400/40 bg-emerald-500/10 text-emerald-400" : "border-[#C6A96B]/20 bg-[#C6A96B]/10 text-[#C6A96B]";
  const actionClass = isDelivery ? "border border-emerald-400 bg-emerald-500/10 text-emerald-400" : "border border-[#C6A96B] bg-[#C6A96B] text-[#0F1115]";

  return <aside className="flex min-h-0 flex-col border-l border-white/10 bg-[#111217]"><header className="border-b border-white/10 px-5 py-5"><div className="flex items-end justify-between"><div><p className={`text-sm ${accentText}`}>CURRENT ORDER</p><h1 className="mt-1 text-2xl font-medium">目前訂單</h1></div><span className={`rounded-full border px-3 py-2 text-sm ${badgeClass}`}>{itemCount} 項</span></div><span className={`mt-3 inline-flex rounded-full border px-3 py-1 text-sm font-medium ${badgeClass}`}>{isDelivery ? "外送模式" : "現場模式"}</span></header>
    <div className="min-h-0 flex-1 overflow-y-auto p-5">{items.length?<ul className="space-y-3">{items.map((item)=><li key={item.id} className="rounded-2xl border border-white/10 bg-[#1A1D23] p-4"><div className="flex justify-between gap-3"><div className="min-w-0"><p className="text-lg font-medium">{item.name}</p>{item.sauce?<p className={`mt-1 text-sm ${accentText}`}>{item.sauce.name}</p>:null}{item.type==="combo"?<p className="mt-1 truncate text-sm text-zinc-500">{item.items.map((part)=>part.name).join(" + ")}</p>:null}<p className="mt-1 text-sm text-zinc-500">${item.price} x {item.qty} = ${item.price*item.qty}</p></div><div className="flex shrink-0 items-center gap-2"><span className="w-8 text-center text-xl font-semibold">{item.qty}</span><button type="button" onClick={()=>onRemoveOne(item.id)} aria-label={`減少一份${item.name}`} className="h-14 w-14 rounded-full border border-white/10 bg-[#0F1115] font-semibold active:scale-95">-1</button></div></div></li>)}</ul>:<div className="flex h-full items-center justify-center text-zinc-600">請點選左側餐點</div>}</div>
    <footer className="border-t border-white/10 bg-[#0F1115] p-5"><p className="mb-2 text-sm text-zinc-400">付款方式</p><div className="mb-4 grid grid-cols-2 gap-2 rounded-2xl bg-[#1A1D23] p-1">{[{id:"cash",label:"現金"},{id:"bank",label:"匯款"}].map((method)=><button key={method.id} type="button" onClick={()=>onPaymentMethodChange(method.id)} className={`min-h-12 rounded-xl font-medium transition ${paymentMethod===method.id?actionClass:"border border-transparent text-zinc-400"}`}>{method.label}</button>)}</div><div className="mb-4 flex items-center justify-between"><span className="text-zinc-400">總計</span><span className={`text-4xl font-semibold ${accentText}`}>${total}</span></div><button type="button" onClick={onCheckout} disabled={!items.length} className={`h-16 w-full rounded-2xl text-xl font-semibold transition active:scale-[.99] disabled:border-transparent disabled:bg-[#2B2F38] disabled:text-zinc-600 ${actionClass}`}>結帳</button></footer></aside>;
}
